CREATE TABLE PAYMENT (
    PAYMENT_ID NUMBER(5) PRIMARY KEY,
    ORDER_ID NUMBER(5),
    PAYMENT_MODE VARCHAR2(30) NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    PAYMENT_AMOUNT NUMBER(10,2) NOT NULL,
    PAYMENT_STATUS VARCHAR2(30) NOT NULL,
    CONSTRAINT FK_PAYMENT_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID)
);
Table created

INSERT INTO PAYMENT VALUES
(1, 1001, 'UPI', DATE '2026-09-22', 1198.00, 'Successful');
1 row created.
INSERT INTO PAYMENT VALUES
(2, 1002, 'Card', DATE '2026-09-22', 999.00, 'Successful');
1 row created.
INSERT INTO PAYMENT VALUES
(3, 1003, 'UPI', DATE '2026-09-23', 599.00, 'Successful');
1 row created.
INSERT INTO PAYMENT VALUES
(4, 1004, 'Cash on Delivery', DATE '2026-09-23', 449.00, 'Successful');
1 row created.
INSERT INTO PAYMENT VALUES
(5, 1005, 'Card', DATE '2026-09-24', 349.00, 'Failed');
1 row created.
INSERT INTO PAYMENT VALUES
(6, 1006, 'UPI', DATE '2026-09-24', 799.00, 'Pending');
1 row created.
COMMIT;
Commit complete.

SELECT *
FROM PAYMENT
WHERE PAYMENT_STATUS = 'Successful';

SELECT *
FROM PAYMENT
WHERE PAYMENT_STATUS = 'Failed';

SELECT *
FROM PAYMENT
WHERE PAYMENT_STATUS = 'Pending';

SELECT PAYMENT_MODE, COUNT(*) AS TOTAL_TRANSACTIONS
FROM PAYMENT
GROUP BY PAYMENT_MODE;

SELECT PAYMENT_MODE, SUM(PAYMENT_AMOUNT) AS TOTAL_AMOUNT
FROM PAYMENT
GROUP BY PAYMENT_MODE;

SELECT
    P.PAYMENT_ID,
    P.ORDER_ID,
    P.PAYMENT_MODE,
    P.PAYMENT_DATE,
    P.PAYMENT_AMOUNT,
    P.PAYMENT_STATUS,
    O.ORDER_STATUS
FROM PAYMENT P
JOIN ORDERS O
ON P.ORDER_ID = O.ORDER_ID
ORDER BY P.PAYMENT_ID;