CREATE TABLE REVIEW (
    REVIEW_ID NUMBER(5) PRIMARY KEY,
    CUSTOMER_ID NUMBER(5),
    PRODUCT_ID NUMBER(5),
    REVIEW_TEXT VARCHAR2(500),
    REVIEW_DATE DATE,
    CONSTRAINT FK_REVIEW_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_REVIEW_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT(PRODUCT_ID)
);

Table created.

CREATE TABLE RATING (
    RATING_ID NUMBER(5) PRIMARY KEY,
    CUSTOMER_ID NUMBER(5),
    PRODUCT_ID NUMBER(5),
    RATING NUMBER(1) NOT NULL,
    RATING_DATE DATE NOT NULL,
    CONSTRAINT FK_RATING_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_RATING_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT CHK_RATING
        CHECK (RATING BETWEEN 1 AND 5)
);
Table created

INSERT INTO REVIEW VALUES
(1, 1, 1, 'Good quality necklace', DATE '2026-10-01');
1 row created
INSERT INTO REVIEW VALUES
(2, 2, 2, 'Beautiful earrings', DATE '2026-10-02');
1 row created
INSERT INTO REVIEW VALUES
(3, 3, 3, 'Nice bracelet', DATE '2026-10-03');
1 row created
INSERT INTO REVIEW VALUES
(4, 4, 4, 'Good quality anklet', DATE '2026-10-04');
1 row created
INSERT INTO REVIEW VALUES
(5, 5, 5, 'Excellent ring', DATE '2026-10-05');
1 row created
COMMIT;
commit completed

INSERT INTO RATING VALUES
(1, 1, 1, 5, DATE '2026-10-01');
1 row created
INSERT INTO RATING VALUES
(2, 2, 2, 4, DATE '2026-10-02');
1 row created
INSERT INTO RATING VALUES
(3, 3, 3, 5, DATE '2026-10-03');
1 row created
INSERT INTO RATING VALUES
(4, 4, 4, 3, DATE '2026-10-04');
1 row created
INSERT INTO RATING VALUES
(5, 5, 5, 4, DATE '2026-10-05');
1 row created
COMMIT;
commit completed

SELECT
    C.CUSTOMER_ID,
    R.REVIEW_ID,
    R.REVIEW_TEXT,
    R.REVIEW_DATE
FROM CUSTOMER C
JOIN REVIEW R
ON C.CUSTOMER_ID = R.CUSTOMER_ID
ORDER BY R.REVIEW_ID;

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    R.RATING_ID,
    R.RATING,
    R.RATING_DATE
FROM PRODUCT P
JOIN RATING R
ON P.PRODUCT_ID = R.PRODUCT_ID
ORDER BY R.RATING_ID;

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    AVG(R.RATING) AS AVERAGE_RATING
FROM PRODUCT P
JOIN RATING R
ON P.PRODUCT_ID = R.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY AVERAGE_RATING DESC;

SELECT
    PRODUCT_ID,
     AVG(RATING) AS AVERAGE_RATING
    FROM RATING
    GROUP BY PRODUCT_ID
    HAVING AVG(RATING) >= 4
    ORDER BY AVERAGE_RATING DESC;


SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    AVG(R.RATING) AS AVERAGE_RATING
FROM PRODUCT P, RATING R
WHERE P.PRODUCT_ID = R.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
HAVING AVG(R.RATING) >= 4
ORDER BY AVERAGE_RATING DESC;